name:                desert-plains
version:             0.1.0.0
github:              "goncharovnikita/desert-plains"
license:             MIT
author:              "Goncharov Nikita"
maintainer:          "goncharovnikita.dev@gmail.com"
copyright:           "2022 Goncharov Nikita"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/goncharovnikita/desert-plains#readme>

default-extensions: NoImplicitPrelude
                  , OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- classy-prelude
- parsec
- mtl
- fsnotify

library:
  source-dirs: src

executables:
  desert-plains-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - desert-plains

tests:
  desert-plains:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - desert-plains
    - hspec
