name: Test

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2

      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: "8.10.7"
          cabal-version: "3.6.2.0"
          enable-stack: true
          stack-no-global: true
          stack-version: "2.7.3"
          stack-setup-ghc: true

      - name: Run test
        run: make test

      - name: Cache stack work
        uses: actions/cache@v2
        with:
          path: |
            ./stack-work
          key: ${{ runner.os }}-${{ hashFiles('./stack.yaml.lock') }}
